name: PROD E2E TESTS

# Run on PR against master
on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run TestCafe tests
      uses: DevExpress/testcafe-action@latest
      with:
          args: "chrome"
    env:
      GIT_ENV: productionsss
